name: M3U Listesini Guncelle

on:
  schedule:
    - cron: '0 6 * * *' # Her gün sabah saat 06:00'da çalışır
  workflow_dispatch: # Manuel tetikleme butonu

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Çek
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Gerekli Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Scraper Scriptini Çalıştır
      run: python scraper.py

    - name: Değişiklikleri Kaydet ve GitHub'a Gönder
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Dosya başarılı bir şekilde oluştuysa commit at
        if [ -f "playlist.m3u" ]; then
          git add playlist.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Otomatik Güncelleme: M3U listesi yenilendi" && git push)
          echo "İşlem tamamlandı."
        else
          echo "UYARI: playlist.m3u dosyası bulunamadı! Scraper çalışmadı veya link bulamadı."
          exit 1
        fi
